import type { AppProps } from 'next/app';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import AppBar from '@/components/AppBar';
import SideBar from '@/components/SideBar';
import styles from '@/styles/App.module.css';
import '@/styles/index.css';

function MyApp({ Component, pageProps }: AppProps) {
  const router = useRouter();

  return (
    <div className={styles.app}>
      <Head>
        <title>Next Archetype by Jung</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <AppBar />
      <SideBar isMain={router.pathname === '/'} />
      <main className={styles.main}>
        <Component {...pageProps} />
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          rel="noopener noreferrer"
          target="_blank"
        >
          Powered by{' '}
          <span className="logo">
            <Image alt="Vercel Logo" height={16} src="/vercel.svg" width={72} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export default MyApp;
