import type { AppProps } from 'next/app'
import Head from 'next/head'
import Image from 'next/image'
import cn from 'classnames'
import AppBar from '@/components/AppBar'
import Background from '@/components/Background'
import styles from '@/styles/Home.module.css'
import '@/styles/globals.css'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Archetype by Jung</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className={cn(['bg-background text-info', styles.main])}>
        <AppBar />
        <Background />
        <Component {...pageProps} />
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            rel="noopener noreferrer"
            target="_blank"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image
                alt="Vercel Logo"
                height={16}
                src="/vercel.svg"
                width={72}
              />
            </span>
          </a>
        </footer>
      </main>
    </div>
  )
}

export default MyApp
